### ISSUE TITLE
Generate Database Automatically 

### ISSUE THREAD

**Issue by Hassankashi** [garora/blogit#5]
Dear @garora , I made a ridiculous mistake and it was I forced to make a relationship with parent table while I have not built child table. I have to change some mismatch with nuget (jquery and angular, fluent, microsoft.build) with blogit , I am so so sorrrry for my bad promise . I try to finish it by Wednesday.

**Comment by garora** [comment]
@Hassankashi - its ok. We developers generally did mistakes and learn from our mistakes, its our right :+1:  No need to worry,

Let me know if I can assist you to figure it out.

**Comment by garora** [comment]
@Hassankashi - I will close this as soon as you push your changes :+1:

**Comment by Hassankashi** [comment]
I am doing until tonight

**Comment by garora** [comment]
Automatically DB creation completed. I will create another request for UI
